hello:
  path: /hello
  controller: App\Controller\HelloController::index

post:
  path: /post
  controller: App\Controller\HelloController::post

home:
  path: /
  controller: App\Controller\HomeController::index
  methods: [GET, POST]

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Admin


view:
  path: /{slug}
  controller: App\Controller\HomeController::view
  methods: [GET]

tag_posts:
  path: /tag/{id}
  controller: App\Controller\TagController::posts
  methods: [GET]

category_posts:
  path: /category/{id}
  controller: App\Controller\CategoryController::posts
  methods: [GET]

