hello:
  path: /hello
  controller: App\Controller\HelloController::index

post:
  path: /post
  controller: App\Controller\HelloController::post

home:
  path: /
  controller: App\Controller\HomeController::index
  methods: [GET, POST]

fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# Admin
admin_dashboard:
  path: /admin
  controller: App\Admin\Controller\DashboardController::index
  methods: [GET]

admin_add_post:
  path: /admin/post/add
  controller: App\Admin\Controller\PostController::add
  methods: [GET, POST]

admin_users:
  path: /admin/users
  controller: App\Admin\Controller\UserController::index

admin_assign_user_role:
  path: /admin/user/promote
  controller: App\Admin\Controller\UserController::promote
  methods: [POST, PUT]

view:
  path: /{slug}
  controller: App\Controller\HomeController::view
  methods: [GET]

tag_posts:
  path: /tag/{id}
  controller: App\Controller\TagController::posts
  methods: [GET]

category_posts:
  path: /category/{id}
  controller: App\Controller\CategoryController::posts
  methods: [GET]

